protected/models/Documento.php
<?php

/**
 * This is the model class for table "documento".
 *
 * The followings are the available columns in table 'documento':
 * @property integer $idDocumento
 * @property string $rutaDoc
 * @property string $nombreDoc
 * @property string $sizeDoc
 * @property string $fechaDoc
 * @property integer $CategoriaDocumento_idCategoriaDocumento
 * @property integer $Usuario_idUsuario
 *
 * The followings are the available model relations:
 * @property Categoriadocumento $categoriaDocumentoIdCategoriaDocumento
 * @property Usuario $usuarioIdUsuario
 */
class Documento extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'documento';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('rutaDoc, nombreDoc, sizeDoc, fechaDoc, CategoriaDocumento_idCategoriaDocumento, Usuario_idUsuario', 'required'),
			array('CategoriaDocumento_idCategoriaDocumento, Usuario_idUsuario', 'numerical', 'integerOnly'=>true),
			array('rutaDoc', 'file','types'=>'pdf', 'allowEmpty'=>true, 'on'=>'update'),
			array('rutaDoc', 'length', 'max'=>255, 'on'=>'insert,update'),
			array('rutaDoc, nombreDoc, sizeDoc', 'length', 'max'=>200),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('idDocumento, rutaDoc, nombreDoc, sizeDoc, fechaDoc, CategoriaDocumento_idCategoriaDocumento, Usuario_idUsuario', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'categoriaDocumentoIdCategoriaDocumento' => array(self::BELONGS_TO, 'Categoriadocumento', 'CategoriaDocumento_idCategoriaDocumento'),
			'usuarioIdUsuario' => array(self::BELONGS_TO, 'Usuario', 'Usuario_idUsuario'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idDocumento' => 'Id Documento',
			'rutaDoc' => 'Documento',
			'nombreDoc' => 'Nombre',
			'sizeDoc' => 'Tamaño',
			'fechaDoc' => 'Fecha',
			'CategoriaDocumento_idCategoriaDocumento' => 'Categoría',
			'Usuario_idUsuario' => 'Subido por',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idDocumento',$this->idDocumento);
		$criteria->compare('rutaDoc',$this->rutaDoc,true);
		$criteria->compare('nombreDoc',$this->nombreDoc,true);
		$criteria->compare('sizeDoc',$this->sizeDoc,true);
		$criteria->compare('fechaDoc',$this->fechaDoc,true);
		$criteria->compare('CategoriaDocumento_idCategoriaDocumento',$this->CategoriaDocumento_idCategoriaDocumento);
		$criteria->compare('Usuario_idUsuario',$this->Usuario_idUsuario);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Documento the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public static function getNombreCategoria($idCategoria){
		$nombre = null;
		$Cat = CategoriaDocumento::model()->findByAttributes(array('idCategoriaDocumento'=>$idCategoria));
		if($Cat != null){
			$nombre = $Cat->nombreCatDoc;
		}
		return $nombre;
	}

	
}

protected/controllers/DocumentoController.php
<?php

class DocumentoController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','download'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','download','documentossubidos'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','download'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Documento;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Documento']))
		{
			$model->attributes=$_POST['Documento'];
			$rnd = rand(0,99999);

			$uploadedFile = CUploadedFile::getInstance($model,'rutaDoc');
			$fileName = "{$rnd}-{$uploadedFile}";

            $model->rutaDoc = $fileName;
            $bytes = $uploadedFile->getSize();
            $bytesString = Util::sizeFile($bytes);
            $model->sizeDoc = $bytesString;

			if($model->save()){
				$uploadedFile->saveAs(Yii::app()->basePath.'/../archivos/documentos/'.$fileName);
				$this->redirect(array('view','id'=>$model->idDocumento));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Documento']))
		{
			$_POST['Banner']['rutaDoc'] = $model->rutaDoc;
			$model->attributes=$_POST['Documento'];

			$uploadedFile=CUploadedFile::getInstance($model,'rutaDoc');

			if($model->save()){
				if(!empty($uploadedFile))  // check if uploaded file is set or not
                {
                    $uploadedFile->saveAs(Yii::app()->basePath.'/../archivos/documentos/'.$model->rutaDoc);
                }
				$this->redirect(array('view','id'=>$model->idDocumento));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Documento');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	public function actionDocumentosSubidos()
	{
		$criteria = new CDbCriteria;
		$criteria->condition = "Usuario_idUsuario=:idUsuario";
		$criteria->params = array(':idUsuario' => Yii::app()->user->getId());

		$dataProvider=new CActiveDataProvider('Documento',array(
			'criteria'=>$criteria,
			));

		$this->render('documentospropios',array(
			'dataProvider'=>$dataProvider,
			'criteria'=>$criteria,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Documento('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Documento']))
			$model->attributes=$_GET['Documento'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Documento::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='documento-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionDownload($id){
		$model=$this->loadModel($id);
		$path = Yii::getPathOfAlias('webroot')."/archivos/documentos/".$model->rutaDoc;
		//$path = Yii::app()->basePath.'/../archivos/documentos/'.$model->rutaDoc;
		
  		$this->downloadFile($path);
	}

	public function downloadFile($fullpath){
  if(!empty($fullpath)){ 
      header("Content-type:application/pdf"); //for pdf file
      //header('Content-Type:text/plain; charset=ISO-8859-15');
      //if you want to read text file using text/plain header 
      header('Content-Disposition: attachment; filename="'.basename($fullpath).'"'); 
      header('Content-Length: ' . filesize($fullpath));
      readfile($fullpath);
      Yii::app()->end();
  }
}
}

protected/views/documento/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'documento-form',
	'enableAjaxValidation'=>false,
	'htmlOptions' => array(
        'enctype' => 'multipart/form-data',
    ),
)); ?>

	<p class="help-block">Los campos con <span class="required">*</span> son necesarios.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php //echo $form->textFieldRow($model,'rutaDoc',array('class'=>'span5','maxlength'=>45)); ?>

	

    <?php if($model->isNewRecord!='1'){ ?>
    	
    <?php echo '<a style="color:black" href="'.Yii::app()->createUrl('documento/download',array('id'=>$model->idDocumento)).'">Descargar archivo <br/><i style="color:black" class="fa fa-download fa-2x" aria-hidden="true"></i></a>'; ?>
    <br/><br/>
    <?php } ?>


    <?php echo $form->labelEx($model,'rutaDoc'); ?>
	<i class="fa fa-upload" aria-hidden="true"></i>
    <?php echo CHtml::activeFileField($model, 'rutaDoc'); ?>

    <?php echo $form->error($model,'rutaDoc'); ?>
<br/><br/>
	<?php echo $form->textFieldRow($model,'nombreDoc',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->hiddenField($model,'sizeDoc',array('value'=>4000)); ?>

	<?php //echo $form->textFieldRow($model,'fechaDoc',array('class'=>'span5')); ?>

	<?php 
		$hoy = date("Y-m-d"); 
		echo $form->hiddenField($model,'fechaDoc',array('value'=>$hoy)); 
	?>

	<?php //echo $form->textFieldRow($model,'CategoriaDocumento_idCategoriaDocumento',array('class'=>'span5')); ?>

	<?php echo $form->dropdownlistrow($model,'CategoriaDocumento_idCategoriaDocumento',CHtml::listData( CategoriaDocumento::model()->findAll(), 'idCategoriaDocumento', 'nombreCatDoc'),array('class'=>'span3',"style"=>"margin-left: 5px;")); ?>

	<?php echo $form->hiddenField($model,'Usuario_idUsuario',array('value'=>Yii::app()->user->getId())); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Crear' : 'Guardar',
			'htmlOptions'=>array(
				'class'=>'botonForm',
				),
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/documento/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'idDocumento',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'rutaDoc',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->textFieldRow($model,'nombreDoc',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->textFieldRow($model,'sizeDoc',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->textFieldRow($model,'fechaDoc',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'CategoriaDocumento_idCategoriaDocumento',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'Usuario_idUsuario',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Buscar',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/documento/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('idDocumento')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idDocumento),array('view','id'=>$data->idDocumento)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('rutaDoc')); ?>:</b>
	<?php echo CHtml::encode($data->rutaDoc); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nombreDoc')); ?>:</b>
	<?php echo CHtml::encode($data->nombreDoc); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('sizeDoc')); ?>:</b>
	<?php echo CHtml::encode($data->sizeDoc); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fechaDoc')); ?>:</b>
	<?php echo CHtml::encode($data->fechaDoc); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('CategoriaDocumento_idCategoriaDocumento')); ?>:</b>
	<?php echo CHtml::encode($data->CategoriaDocumento_idCategoriaDocumento); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Usuario_idUsuario')); ?>:</b>
	<?php echo CHtml::encode($data->Usuario_idUsuario); ?>
	<br />


</div>

protected/views/documento/create.php
<?php
$this->breadcrumbs=array(
	'Documentos'=>array('index'),
	'Crear',
);

$this->menu=array(
	array('label'=>'Listar Documento','url'=>array('index')),
	array('label'=>'Mis documentos subidos','url'=>array('documentossubidos')),
	array('label'=>'Documentos Disponibles','url'=>array('index')),
	//array('label'=>'Administrar Documento','url'=>array('admin')),
);
?>

<h1>Nuevo Documento</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/documento/documentospropios.php
<?php

$this->menu=array(
	array('label'=>'Nuevo Documento','url'=>array('create')),
	array('label'=>'Mis documentos subidos','url'=>array('documentossubidos')),
	array('label'=>'Documentos Disponibles','url'=>array('index')),
	//array('label'=>'Administrar Alerta','url'=>array('admin')),
);
?>

<h1>Documentos</h1>
<div class="coloradd icon-block">
<a href="<?php echo Yii::app()->createUrl('documento/create',array());?>">
<img class="mas" src="<?php echo Yii::app()->theme->baseUrl; ?>/img/mas.png">
<span>Nuevo</span>
</a>
</div>
<table class="responstable" style="margin-top: 60px;">
	<thead>
		<tr>
			<th>Categoría</th>
			<th>Nombre Archivo</th>
			<th>Fecha de Subida</th>
			<th>Subido por</th>
			<th>Tamaño</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	$lista = Documento::model()->findAll($criteria);
	if($lista)
	{
		foreach ($lista as $Item) {
			echo '<tr>';
			echo '<td>';
			echo CHtml::link(Documento::getNombreCategoria($Item->CategoriaDocumento_idCategoriaDocumento),Yii::app()->createUrl("categoriadocumento/view/".CHtml::encode($Item->CategoriaDocumento_idCategoriaDocumento)));
			echo '</td>';
			echo '<td>';
			echo $Item->nombreDoc;
			echo '</td>';
			echo '<td>';
			echo $Item->fechaDoc;
			echo '</td>';
			echo '<td>';
			echo Usuario::getNombreUsuario($Item->Usuario_idUsuario);
			echo '</td>';
			echo '<td>';
			echo $Item->sizeDoc;
			echo '</td>';
			
			echo '<td class="opcionestable">';
			echo '<a href="'.Yii::app()->createUrl('documento/view',array('id'=>$Item->idDocumento)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/ver.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('documento/update',array('id'=>$Item->idDocumento)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/editar.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('documento/delete',array('id'=>$Item->idDocumento)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/borrar.png"></a>';
			echo '<i  aria-hidden="true"></i>';
			
			/*
			echo '<td>';
			echo '<a href="'.Yii::app()->createUrl('documento/download',array('id'=>$Item->idDocumento)).'"><i class="fa fa-upload fa-2x" aria-hidden="true"></i></a>';
			
			echo '</td>';
			*/
			echo '</tr>';
		}
	}else{
		echo '<tr><td colspan="6">No se encontraron resultados.</td></tr>';
	}
	?>
	
		
	</tbody>
</table>





<?php 

//$this->widget('bootstrap.widgets.TbListView',array(	'dataProvider'=>$dataProvider,	'itemView'=>'_view',)); 
?>

protected/views/documento/index.php
<?php

$this->menu=array(
	array('label'=>'Nuevo Documento','url'=>array('create')),
	array('label'=>'Mis documentos subidos','url'=>array('documentossubidos')),
	array('label'=>'Documentos Disponibles','url'=>array('index')),
	//array('label'=>'Administrar Alerta','url'=>array('admin')),
);
?>

<h1>Documentos Disponibles</h1>
<div class="coloradd icon-block">
<a href="<?php echo Yii::app()->createUrl('documento/create',array());?>">
<img class="mas" src="<?php echo Yii::app()->theme->baseUrl; ?>/img/mas.png">
<span>Nuevo</span>
</a>
</div>
<table class="responstable" style="margin-top: 60px;">
	<thead>
		<tr>
			
			<th>Nombre Archivo</th>
			<th>Fecha de Subida</th>
			<!--<th>Subido por</th>-->
			<th>Categoría</th>
			<th>Acciones</th>
			<th>Descarga</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	$lista = Documento::model()->findAll();
	if($lista)
	{
		foreach ($lista as $Item) {
			echo '<tr>';
			echo '<td>';
			echo $Item->nombreDoc;
			echo '</td>';
			/*echo '<td>';
			echo Usuario::getNombreUsuario($Item->Usuario_idUsuario);
			echo '</td>';*/
			echo '<td>';
			echo $Item->fechaDoc;
			echo '</td>';
			echo '<td>';
			echo CHtml::link(Documento::getNombreCategoria($Item->CategoriaDocumento_idCategoriaDocumento),Yii::app()->createUrl("categoriadocumento/view/".CHtml::encode($Item->CategoriaDocumento_idCategoriaDocumento)));
			echo '</td>';
			/*
			echo '<td>';
			echo $Item->sizeDoc;
			echo '</td>';
			*/
			echo '<td class="opcionestable">';
			echo '<a href="'.Yii::app()->createUrl('documento/view',array('id'=>$Item->idDocumento)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/ver.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('documento/update',array('id'=>$Item->idDocumento)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/editar.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('documento/delete',array('id'=>$Item->idDocumento)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/borrar.png"></a>';
			echo '<i  aria-hidden="true"></i>';
			
			echo '<td>';
			echo '<a href="'.Yii::app()->createUrl('documento/download',array('id'=>$Item->idDocumento)).'"><i style="color:black" class="fa fa-download fa-lg " aria-hidden="true"></i></a>';
			
			echo '</td>';
			echo '</tr>';
		}
	}
	?>
	
		
	</tbody>
</table>





<?php 

//$this->widget('bootstrap.widgets.TbListView',array(	'dataProvider'=>$dataProvider,	'itemView'=>'_view',)); 
?>

protected/views/documento/update.php
<?php
$this->breadcrumbs=array(
	'Documentos'=>array('index'),
	$model->idDocumento=>array('view','id'=>$model->idDocumento),
	'Update',
);

$this->menu=array(
	array('label'=>'Listar Documento','url'=>array('index')),
	array('label'=>'Crear Documento','url'=>array('create')),
	array('label'=>'Ver Documento','url'=>array('view','id'=>$model->idDocumento)),
	array('label'=>'Administrar Documento','url'=>array('admin')),
);
?>

<h1>Editar: <?php echo $model->nombreDoc; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/documento/view.php
<?php
$this->breadcrumbs=array(
	'Documentos'=>array('index'),
	$model->idDocumento,
);

$this->menu=array(
	array('label'=>'Listar Documento','url'=>array('index')),
	array('label'=>'Crear Documento','url'=>array('create')),
	array('label'=>'Modificar Documento','url'=>array('update','id'=>$model->idDocumento)),
	array('label'=>'Eliminar Documento','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->idDocumento),'confirm'=>'Esta seguro de eliminar este item?')),
	//array('label'=>'Administrar Documento','url'=>array('admin')),
);
?>

<h1><?php echo $model->nombreDoc; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'rutaDoc',
		'nombreDoc',
		'sizeDoc',
		'fechaDoc',
		'CategoriaDocumento_idCategoriaDocumento'=>array(
			'name'=>'CategoriaDocumento_idCategoriaDocumento',
			'value'=>Documento::getNombreCategoria($model->CategoriaDocumento_idCategoriaDocumento),
			),
		'Usuario_idUsuario'=>array(
			'name'=>'Usuario_idUsuario',
			'value'=>Usuario::getNombreUsuario($model->Usuario_idUsuario),
			),
		'custom'=>array(
			'name'=>'Descargar',
			'label'=>'Descargar',
			'type'=>'raw',
			'value'=>'<a style="color:black;" href="'.Yii::app()->createUrl('documento/download',array('id'=>$model->idDocumento)).'"><i class="fa fa-download fa-lg" aria-hidden="true"></i></a>',
			),
		
	),
)); ?>