protected/models/Capacitacion.php
<?php

/**
 * This is the model class for table "capacitacion".
 *
 * The followings are the available columns in table 'capacitacion':
 * @property integer $idCapacitacion
 * @property string $descripcionCap
 * @property string $tituloCap
 * @property string $imagenCap
 * @property integer $Usuario_idUsuario
 * @property string $fechaCap
 * @property integer $estadoCap
 * @property string $fechaLimCap
 *
 * The followings are the available model relations:
 * @property Usuario $usuarioIdUsuario
 * @property Formcapacitacion[] $formcapacitacions
 */
class Capacitacion extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'capacitacion';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('descripcionCap, tituloCap, imagenCap, Usuario_idUsuario, fechaCap, estadoCap, fechaLimCap', 'required'),
			array('Usuario_idUsuario, estadoCap', 'numerical', 'integerOnly'=>true),
			array('imagenCap', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'),
			array('imagenCap', 'length', 'max'=>255, 'on'=>'insert,update'),
			array('descripcionCap', 'length', 'max'=>15000),
			array('tituloCap', 'length', 'max'=>45),
			array('imagenCap', 'length', 'max'=>100),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('idCapacitacion, descripcionCap, tituloCap, imagenCap, Usuario_idUsuario, fechaCap, estadoCap, fechaLimCap', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'usuarioIdUsuario' => array(self::BELONGS_TO, 'Usuario', 'Usuario_idUsuario'),
			'formcapacitacions' => array(self::HAS_MANY, 'Formcapacitacion', 'Capacitacion_idCapacitacion'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idCapacitacion' => 'Id Capacitacion',
			'descripcionCap' => 'Contenido',
			'tituloCap' => 'Título',
			'imagenCap' => 'Imagen',
			'Usuario_idUsuario' => 'Creado por',
			'fechaCap' => 'Fecha',
			'estadoCap' => 'Estado',
			'fechaLimCap' => 'Fecha Término',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idCapacitacion',$this->idCapacitacion);
		$criteria->compare('descripcionCap',$this->descripcionCap,true);
		$criteria->compare('tituloCap',$this->tituloCap,true);
		$criteria->compare('imagenCap',$this->imagenCap,true);
		$criteria->compare('Usuario_idUsuario',$this->Usuario_idUsuario);
		$criteria->compare('fechaCap',$this->fechaCap,true);
		$criteria->compare('estadoCap',$this->estadoCap);
		$criteria->compare('fechaLimCap',$this->fechaLimCap,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Capacitacion the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	
}

protected/controllers/CapacitacionController.php
<?php

class CapacitacionController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Capacitacion;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Capacitacion']))
		{
			$rnd = rand(0,9999);  // generate random number between 0-9999
			$model->attributes=$_POST['Capacitacion'];

			$uploadedFile=CUploadedFile::getInstance($model,'imagenCap');
            $fileName = "{$rnd}-{$uploadedFile}";  // random number + file name
            $model->imagenCap = $fileName;
            
			if($model->save()){

				$uploadedFile->saveAs(Yii::app()->basePath.'/../archivos/imagenes/'.$fileName);
				$this->redirect(array('view','id'=>$model->idCapacitacion));

			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Capacitacion']))
		{
			$_POST['Banner']['imagenCap'] = $model->imagenCap;
			$model->attributes=$_POST['Capacitacion'];

			$uploadedFile=CUploadedFile::getInstance($model,'imagenCap');

			if($model->save()){
				if(!empty($uploadedFile))  // check if uploaded file is set or not
                {
                    $uploadedFile->saveAs(Yii::app()->basePath.'/../archivos/imagenes/'.$model->image);
                }
				$this->redirect(array('view','id'=>$model->idCapacitacion));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Capacitacion');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Capacitacion('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Capacitacion']))
			$model->attributes=$_GET['Capacitacion'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Capacitacion::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='capacitacion-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/capacitacion/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'capacitacion-form',
	'enableAjaxValidation'=>false,
	'htmlOptions' => array(
        'enctype' => 'multipart/form-data',
    ),
)); ?>

	<p class="help-block">Los campos con <span class="required">*</span> son necesarios.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php //echo $form->textFieldRow($model,'descripcionCap',array('class'=>'span5','maxlength'=>15000)); ?>

	<?php echo $form->textFieldRow($model,'tituloCap',array('class'=>'span5','maxlength'=>45)); ?>

	<?php //echo $form->textFieldRow($model,'imagenCap',array('class'=>'span5','maxlength'=>100)); ?>

	<?php echo $form->hiddenField($model,'Usuario_idUsuario',array('value'=>Yii::app()->user->getId())); ?>

	<?php //echo $form->textFieldRow($model,'fechaCap',array('class'=>'span5')); ?>

	<?php 
		$AnioActual = date('Y');
		echo $form->labelEx($model,'fechaCap');
		$this->widget('application.extensions.timepicker.EJuiDateTimePicker',array(
	    'model'=>$model,
	    'attribute'=>'fechaCap',
	    'language' => 'es',
	    'options'=>array(
	    	'showAnim'=>'slide',
	        'dateFormat'=>'yy-mm-dd',
			'changeMonth'=>true,
	        'changeYear'=>true,
			'yearRange'=>($AnioActual-100).':'.$AnioActual,
			'showHour'=> false,
			'showMinute'=>false,
			'showTime'=>false,
			'timeFormat'=>'',
	        ),
	    )); 
	 ?>

	<?php //echo $form->textFieldRow($model,'estadoCap',array('class'=>'span5')); ?>

	<?php //<?php echo $form->textFieldRow($model,'estadoAlerta',array('class'=>'span5','maxlength'=>45)); 
		$seleccionado = array();
		if(!$model->isNewRecord){
			$seleccionado = array($model->estadoCap=>array('selected'=>true));
		}
		
		$Pregunta = "Escoja el estado de la Capacitación";
		$ListaOpciones = array('0'=>"Activado", '1'=>"Desactivado");

		echo $form->dropDownListRow($model,'estadoCap',$ListaOpciones,array('options'=>$seleccionado,'class'=>'span5', 'prompt'=>$Pregunta));
		

	?>

	<?php //echo $form->textFieldRow($model,'fechaLimCap',array('class'=>'span5')); ?>

	<?php 
		$AnioActual = date('Y');
		echo $form->labelEx($model,'fechaLimCap');
		$this->widget('application.extensions.timepicker.EJuiDateTimePicker',array(
	    'model'=>$model,
	    'attribute'=>'fechaLimCap',
	    'language' => 'es',
	    'options'=>array(
	    	'showAnim'=>'slide',
	        'dateFormat'=>'yy-mm-dd',
			'changeMonth'=>true,
	        'changeYear'=>true,
			'yearRange'=>($AnioActual-100).':'.$AnioActual,
			'showHour'=> false,
			'showMinute'=>false,
			'showTime'=>false,
			'timeFormat'=>'',
	        ),
	    )); 
	 ?>

	<?php echo $form->textAreaRow($model,'descripcionCap',array('class'=>'textAreaCont','maxlength'=>15000)); ?>

	<?php echo $form->labelEx($model,'imagenCap'); ?>
	<i class="fa fa-upload" aria-hidden="true"></i>

    <?php echo CHtml::activeFileField($model, 'imagenCap'); ?>
    <?php echo $form->error($model,'imagenCap'); ?>

    <br/>
	<?php if($model->isNewRecord!='1'){ ?>
		<div>
     	<?php echo CHtml::image(Yii::app()->request->baseUrl.'/archivos/imagenes/'.$model->imagenCap,"imagenCap",array("width"=>200)); ?>
	</div>

	<?php } ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Crear' : 'Guardar',
			'htmlOptions'=>array(
				'class'=>'botonForm',
				),
		)); ?>
	</div>

<?php $this->endWidget(); ?>
<?php
$baseUrl = Yii::app()->theme->baseUrl;; 
$cs = Yii::app()->getClientScript();
$cs->registerScriptFile($baseUrl.'/js/tinymce/tinymce.min.js');
?>

<script>
	tinymce.init({ 
			selector:'textarea', 
			language:'es_MX', 
			plugins: 'lists wordcount insertdatetime preview',
			elementpath: false,
			fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt",
			toolbar: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | table | fontsizeselect"
	});
	 document.getElementById('message_ifr').removeAttribute('title');
</script>

protected/views/capacitacion/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'idCapacitacion',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'descripcionCap',array('class'=>'span5','maxlength'=>15000)); ?>

	<?php echo $form->textFieldRow($model,'tituloCap',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->textFieldRow($model,'imagenCap',array('class'=>'span5','maxlength'=>100)); ?>

	<?php echo $form->textFieldRow($model,'Usuario_idUsuario',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'fechaCap',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'estadoCap',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'fechaLimCap',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Buscar',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/capacitacion/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('idCapacitacion')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idCapacitacion),array('view','id'=>$data->idCapacitacion)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('descripcionCap')); ?>:</b>
	<?php echo CHtml::encode($data->descripcionCap); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tituloCap')); ?>:</b>
	<?php echo CHtml::encode($data->tituloCap); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('imagenCap')); ?>:</b>
	<?php echo CHtml::encode($data->imagenCap); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Usuario_idUsuario')); ?>:</b>
	<?php echo CHtml::encode($data->Usuario_idUsuario); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fechaCap')); ?>:</b>
	<?php echo CHtml::encode($data->fechaCap); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('estadoCap')); ?>:</b>
	<?php echo CHtml::encode($data->estadoCap); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('fechaLimCap')); ?>:</b>
	<?php echo CHtml::encode($data->fechaLimCap); ?>
	<br />

	*/ ?>

</div>

protected/views/capacitacion/create.php
<?php
$this->breadcrumbs=array(
	'Capacitacions'=>array('index'),
	'Crear',
);

$this->menu=array(
	array('label'=>'Listar Capacitación','url'=>array('index')),
	//array('label'=>'Administrar Capacitacion','url'=>array('admin')),
);
?>

<h1>Nueva Capacitación</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/capacitacion/index.php
<?php

$this->menu=array(
	array('label'=>'Nuevo Documento','url'=>array('create')),
	//array('label'=>'Administrar Alerta','url'=>array('admin')),
);
?>

<h1>Capacitaciones</h1>
<div class="coloradd icon-block">
<a href="<?php echo Yii::app()->createUrl('capacitacion/create',array());?>">
<img class="mas" src="<?php echo Yii::app()->theme->baseUrl; ?>/img/mas.png">
<span>Nuevo</span>
</a>
</div>
<table class="responstable" style="margin-top: 60px;">
	<thead>
		<tr>
			<th>Título</th>
			<th>Fecha</th>
			<th>Fecha Límite</th>
			<th>Estado</th>
			<th>Acciones</th>
			<th>Lista de Inscritos</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	$lista = Capacitacion::model()->findAll();
	if($lista)
	{
		foreach ($lista as $Item) {
			echo '<tr>';
			echo '<td>';
			echo $Item->tituloCap;
			echo '</td>';
			echo '<td>';
			echo $Item->fechaCap;
			echo '</td>';
			echo '<td>';
			echo $Item->fechaLimCap;
			echo '</td>';
			echo '<td>';
			echo $Item->estadoCap ? "Inactivo": "Activo";
			echo '</td>';
			
			
			echo '<td class="opcionestable">';
			echo '<a href="'.Yii::app()->createUrl('capacitacion/view',array('id'=>$Item->idCapacitacion)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/ver.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('capacitacion/update',array('id'=>$Item->idCapacitacion)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/editar.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('capacitacion/delete',array('id'=>$Item->idCapacitacion)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/borrar.png"></a>';
			echo '<i  aria-hidden="true"></i>';
			
			
			echo '<td>';
			//<img class="imagenView" src="/onemi-prev/themes/bootstrap/img/ver.png">
			/*
			echo '<a href="'.Yii::app()->createUrl('formcapacitacion/index2',array('id'=>$Item->idCapacitacion)).'"><i class="fa fa-user-plus fa-2x" aria-hidden="true"></i></a>';
			*/
			echo '<a href="'.Yii::app()->createUrl('formcapacitacion/index2',array('id'=>$Item->idCapacitacion)).'"><img class="imagenView" src="/onemi-prev/themes/bootstrap/img/mas.png"></a>';
			echo '</td>';
			echo '</tr>';
		}
	}
	?>
	
		
	</tbody>
</table>





<?php 

//$this->widget('bootstrap.widgets.TbListView',array(	'dataProvider'=>$dataProvider,	'itemView'=>'_view',)); 
?>

protected/views/capacitacion/update.php
<?php
$this->breadcrumbs=array(
	'Capacitacions'=>array('index'),
	$model->idCapacitacion=>array('view','id'=>$model->idCapacitacion),
	'Update',
);

$this->menu=array(
	array('label'=>'Listar Capacitacion','url'=>array('index')),
	array('label'=>'Crear Capacitacion','url'=>array('create')),
	//array('label'=>'Ver Capacitacion','url'=>array('view','id'=>$model->idCapacitacion)),
	//array('label'=>'Administrar Capacitacion','url'=>array('admin')),
);
?>

<h1>Editar Capacitación <?php echo $model->tituloCap; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/capacitacion/view.php
<?php
$this->breadcrumbs=array(
	'Capacitacions'=>array('index'),
	$model->idCapacitacion,
);

$this->menu=array(
	array('label'=>'Listar Capacitacion','url'=>array('index')),
	array('label'=>'Crear Capacitacion','url'=>array('create')),
	array('label'=>'Modificar Capacitacion','url'=>array('update','id'=>$model->idCapacitacion)),
	array('label'=>'Eliminar Capacitacion','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->idCapacitacion),'confirm'=>'Esta seguro de eliminar este item?')),
	//array('label'=>'Administrar Capacitacion','url'=>array('admin')),
);
?>

<h1>Capacitación: <?php echo $model->tituloCap; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		//'idCapacitacion',
		
		'tituloCap',
		
		'Usuario_idUsuario'=>array(
			'name'=>'Usuario_idUsuario',
			'value'=>Usuario::getNombreUsuario($model->Usuario_idUsuario),
			),
		'fechaCap'=>array(
			'name'=>'fechaCap',
			'value'=>Util::convertirFechaTexto($model->fechaCap),
		),
		
		'fechaLimCap'=>array(
			'name'=>'fechaLimCap',
			'value'=>Util::convertirFechaTexto($model->fechaLimCap),
		),
		'estadoCap'=>array(
			'name'=>'estadoCap',
			'value'=> $model->estadoCap ? "Inactivo": "Activo",
			),
		
		'descripcionCap'=>array(
			'name'=>'descripcionCap',
			'type'=>'raw',
			//'value'=>'<pre class="viewContentNoticia">'.$model->cuerpoNoticia.'</pre>',
			'value'=>'<div class="viewContentNoticia" align="justify">'.$model->descripcionCap.'</div>',
			),
		'imagenCap'=>array(        
           	'name'=>'imagenCap',
           	'type'=>'raw',
            'value'=>  CHtml::image(Yii::app()->request->baseUrl.'/archivos/imagenes/'.$model->imagenCap,"imagenCap",array("width"=>'100%')),
        ),
	),
)); ?>