protected/models/Noticia.php
<?php

/**
 * This is the model class for table "noticia".
 *
 * The followings are the available columns in table 'noticia':
 * @property integer $idNoticia
 * @property string $tituloNoticia
 * @property string $subtituloNoticia
 * @property string $fechaNoticia
 * @property string $cuerpoNoticia
 * @property string $imagenNoticia
 * @property integer $Usuario_idUsuario
 *
 * The followings are the available model relations:
 * @property Usuario $usuarioIdUsuario
 */
class Noticia extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'noticia';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('tituloNoticia, fechaNoticia, cuerpoNoticia, imagenNoticia, Usuario_idUsuario', 'required'),
			array('Usuario_idUsuario', 'numerical', 'integerOnly'=>true),
			array('imagenNoticia', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'),
			array('imagenNoticia', 'length', 'max'=>255, 'on'=>'insert,update'),
			array('tituloNoticia', 'length', 'max'=>300),
			array('subtituloNoticia', 'length', 'max'=>500),
			array('cuerpoNoticia', 'length', 'max'=>15000),
			array('imagenNoticia', 'length', 'max'=>45),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('idNoticia, tituloNoticia, subtituloNoticia, fechaNoticia, cuerpoNoticia, imagenNoticia, Usuario_idUsuario', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'usuarioIdUsuario' => array(self::BELONGS_TO, 'Usuario', 'Usuario_idUsuario'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idNoticia' => 'Id Noticia',
			'tituloNoticia' => 'Título de la Noticia',
			'subtituloNoticia' => 'Subtítulo Noticia',
			'fechaNoticia' => 'Fecha de Creación',
			'cuerpoNoticia' => 'Contenido',
			'imagenNoticia' => 'Imagen',
			'Usuario_idUsuario' => 'Creado por',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idNoticia',$this->idNoticia);
		$criteria->compare('tituloNoticia',$this->tituloNoticia,true);
		$criteria->compare('subtituloNoticia',$this->subtituloNoticia,true);
		$criteria->compare('fechaNoticia',$this->fechaNoticia,true);
		$criteria->compare('cuerpoNoticia',$this->cuerpoNoticia,true);
		$criteria->compare('imagenNoticia',$this->imagenNoticia,true);
		$criteria->compare('Usuario_idUsuario',$this->Usuario_idUsuario);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Noticia the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/NoticiaController.php
<?php

class NoticiaController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Noticia;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Noticia']))
		{
			$rnd = rand(0,9999);  // generate random number between 0-9999
			$model->attributes=$_POST['Noticia'];

			$uploadedFile=CUploadedFile::getInstance($model,'imagenNoticia');
            $fileName = "{$rnd}-{$uploadedFile}";  // random number + file name
            $model->imagenNoticia = $fileName;

			if($model->save()){
				$uploadedFile->saveAs(Yii::app()->basePath.'/../archivos/imagenes/'.$fileName);
				$this->redirect(array('view','id'=>$model->idNoticia));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Noticia']))
		{
			$_POST['Noticia']['imagenNoticia'] = $model->imagenNoticia;
			$model->attributes=$_POST['Noticia'];

			$uploadedFile=CUploadedFile::getInstance($model,'imagenNoticia');

			if($model->save()){
				if(!empty($uploadedFile))  // check if uploaded file is set or not
                {
                    $uploadedFile->saveAs(Yii::app()->basePath.'/../archivos/imagenes/'.$model->imagenNoticia);
                }
				$this->redirect(array('view','id'=>$model->idNoticia));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Noticia');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Noticia('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Noticia']))
			$model->attributes=$_GET['Noticia'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Noticia::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='noticia-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/noticia/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'noticia-form',
	'enableAjaxValidation'=>false,
	'htmlOptions' => array(
        'enctype' => 'multipart/form-data',
    ),
)); ?>

	<p class="help-block">Los campos con <span class="required">*</span> son necesarios.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'tituloNoticia',array('class'=>'span8','maxlength'=>300)); ?>

	<?php echo $form->textFieldRow($model,'subtituloNoticia',array('class'=>'span8','maxlength'=>500)); ?>

	<?php 
		//echo $form->textFieldRow($model,'imagenNoticia',array('class'=>'span5','maxlength'=>45)); 
	?>

	<?php echo $form->labelEx($model,'imagenNoticia'); ?>
	<i class="fa fa-upload" aria-hidden="true"></i>

    <?php echo CHtml::activeFileField($model, 'imagenNoticia'); ?>
    <?php echo $form->error($model,'imagenNoticia'); ?>

    <br/>
	<?php if($model->isNewRecord!='1'){ ?>
		<div>
     	<?php echo CHtml::image(Yii::app()->request->baseUrl.'/archivos/imagenes/'.$model->imagenNoticia,"imagenNoticia",array("width"=>200)); ?>
	</div>

	<?php } ?>

	<?php 
		$hoy = date("Y-m-d"); 
		echo $form->hiddenField($model,'fechaNoticia',array('value'=>$hoy)); ?>

<br/><br/>
	<?php echo $form->textAreaRow($model,'cuerpoNoticia',array('class'=>'textAreaCont','maxlength'=>15000)); ?>



	<?php echo $form->hiddenField($model,'Usuario_idUsuario',array('value'=>Yii::app()->user->getId())); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Crear' : 'Guardar',
			'htmlOptions'=>array(
				'class'=>'botonForm',
				),
		)); ?>
	</div>

<?php $this->endWidget(); ?>
<?php
$baseUrl = Yii::app()->theme->baseUrl;; 
$cs = Yii::app()->getClientScript();
$cs->registerScriptFile($baseUrl.'/js/tinymce/tinymce.min.js');
?>

<script>
	tinymce.init({ 
			selector:'textarea', 
			language:'es_MX', 
			plugins: 'lists wordcount insertdatetime preview',
			elementpath: false,
			fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt",
			toolbar: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | table | fontsizeselect"
	});
</script>

protected/views/noticia/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'idNoticia',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'tituloNoticia',array('class'=>'span5','maxlength'=>300)); ?>

	<?php echo $form->textFieldRow($model,'subtituloNoticia',array('class'=>'span5','maxlength'=>500)); ?>

	<?php echo $form->textFieldRow($model,'fechaNoticia',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'cuerpoNoticia',array('class'=>'span5','maxlength'=>15000)); ?>

	<?php echo $form->textFieldRow($model,'imagenNoticia',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->textFieldRow($model,'Usuario_idUsuario',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Buscar',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/noticia/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('idNoticia')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idNoticia),array('view','id'=>$data->idNoticia)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tituloNoticia')); ?>:</b>
	<?php echo CHtml::encode($data->tituloNoticia); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('subtituloNoticia')); ?>:</b>
	<?php echo CHtml::encode($data->subtituloNoticia); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fechaNoticia')); ?>:</b>
	<?php echo CHtml::encode($data->fechaNoticia); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('cuerpoNoticia')); ?>:</b>
	<?php echo CHtml::encode($data->cuerpoNoticia); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('imagenNoticia')); ?>:</b>
	<?php echo CHtml::encode($data->imagenNoticia); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Usuario_idUsuario')); ?>:</b>
	<?php echo CHtml::encode($data->Usuario_idUsuario); ?>
	<br />


</div>

protected/views/noticia/create.php
<?php
$this->breadcrumbs=array(
	'Noticias'=>array('index'),
	'Crear',
);

$this->menu=array(
	array('label'=>'Listar Noticia','url'=>array('index')),
	array('label'=>'Administrar Noticia','url'=>array('admin')),
);
?>

<h1>Nueva Noticia</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/noticia/index.php
<?php

$this->menu=array(
	array('label'=>'Nueva Noticia','url'=>array('create')),
	//array('label'=>'Administrar Alerta','url'=>array('admin')),
);
?>

<h1>Noticias</h1>
<div class="coloradd icon-block">
<a href="<?php echo Yii::app()->createUrl('noticia/create',array());?>">
<img class="mas" src="<?php echo Yii::app()->theme->baseUrl; ?>/img/mas.png">
<span>Nuevo</span>
</a>
</div>
<table class="responstable" style="margin-top: 60px;">
	<thead>
		<tr>
			<th>Titulo</th>
			<th>SubTitulo</th>
			<th>Fecha de Creación</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	$lista = Noticia::model()->findAll();
	if($lista)
	{
		foreach ($lista as $Item) {
			echo '<tr>';
			echo '<td>';
			echo $Item->tituloNoticia;
			echo '</td>';
			echo '<td>';
			echo $Item->subtituloNoticia;
			echo '</td>';
			echo '<td>';
			echo $Item->fechaNoticia;
			echo '</td>';			
			echo '<td class="opcionestable">';
			echo '<a href="'.Yii::app()->createUrl('noticia/view',array('id'=>$Item->idNoticia)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/ver.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('noticia/update',array('id'=>$Item->idNoticia)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/editar.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('noticia/delete',array('id'=>$Item->idNoticia)).'"><img class="imagenView" src="'.Yii::app()->theme->baseUrl.'/img/borrar.png"></a>';
			echo '<i  aria-hidden="true"></i>';
			echo '</td>';
			echo '</tr>';
		}
	}
	?>
	
		
	</tbody>
</table>





<?php 

//$this->widget('bootstrap.widgets.TbListView',array(	'dataProvider'=>$dataProvider,	'itemView'=>'_view',)); 
?>

protected/views/noticia/update.php
<?php
$this->breadcrumbs=array(
	'Noticias'=>array('index'),
	$model->idNoticia=>array('view','id'=>$model->idNoticia),
	'Update',
);

$this->menu=array(
	array('label'=>'Listar Noticia','url'=>array('index')),
	array('label'=>'Crear Noticia','url'=>array('create')),
	array('label'=>'Ver Noticia','url'=>array('view','id'=>$model->idNoticia)),
	array('label'=>'Administrar Noticia','url'=>array('admin')),
);
?>

<h1>Editando Noticia: <?php echo $model->tituloNoticia; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/noticia/view.php
<?php
$this->breadcrumbs=array(
	'Noticias'=>array('index'),
	$model->idNoticia,
);

$this->menu=array(
	array('label'=>'Listar Noticia','url'=>array('index')),
	array('label'=>'Crear Noticia','url'=>array('create')),
	array('label'=>'Modificar Noticia','url'=>array('update','id'=>$model->idNoticia)),
	array('label'=>'Eliminar Noticia','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->idNoticia),'confirm'=>'Esta seguro de eliminar este item?')),
	//array('label'=>'Administrar Noticia','url'=>array('admin')),
);
?>

<h1>Viendo Noticia: <?php echo $model->tituloNoticia; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		//'idNoticia',
		'tituloNoticia',
		'subtituloNoticia',
		'fechaNoticia'=>array(
			'name'=>'fechaNoticia',
			'value'=>Util::convertirFechaTexto($model->fechaNoticia),
		),
		'cuerpoNoticia'=>array(
			'name'=>'cuerpoNoticia',
			'type'=>'raw',
			//'value'=>'<pre class="viewContentNoticia">'.$model->cuerpoNoticia.'</pre>',
			'value'=>'<div class="viewContentNoticia" align="justify">'.$model->cuerpoNoticia.'</div>',
			),
		'imagenNoticia'=>array(        
           	'name'=>'imagenNoticia',
           	'type'=>'raw',
            'value'=>  CHtml::image(Yii::app()->request->baseUrl.'/archivos/imagenes/'.$model->imagenNoticia,"imagenNoticia",array("width"=>'100%')),
        ),
		
	),
)); ?>