protected/models/Ruta.php
<?php

/**
 * This is the model class for table "ruta".
 *
 * The followings are the available columns in table 'ruta':
 * @property integer $idRuta
 * @property string $nombreRuta
 * @property string $fechaRuta
 * @property string $textoRuta
 * @property integer $usuario_idUsuario
 *
 * The followings are the available model relations:
 * @property Puntoruta[] $puntorutas
 * @property Usuario $usuarioIdUsuario
 */
class Ruta extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'ruta';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nombreRuta, fechaRuta, usuario_idUsuario', 'required'),
			array('usuario_idUsuario', 'numerical', 'integerOnly'=>true),
			array('nombreRuta, fechaRuta', 'length', 'max'=>45),
			array('textoRuta', 'length', 'max'=>50000),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('idRuta, nombreRuta, fechaRuta, textoRuta, usuario_idUsuario', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'puntorutas' => array(self::HAS_MANY, 'Puntoruta', 'ruta_idRuta'),
			'usuarioIdUsuario' => array(self::BELONGS_TO, 'Usuario', 'usuario_idUsuario'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idRuta' => 'Id Ruta',
			'nombreRuta' => 'Nombre de la Ruta',
			'fechaRuta' => 'Fecha',
			'textoRuta' => 'Texto',
			'usuario_idUsuario' => 'Usuario Id Usuario',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idRuta',$this->idRuta);
		$criteria->compare('nombreRuta',$this->nombreRuta,true);
		$criteria->compare('fechaRuta',$this->fechaRuta,true);
		$criteria->compare('textoRuta',$this->textoRuta,true);
		$criteria->compare('usuario_idUsuario',$this->usuario_idUsuario);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Ruta the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/RutaController.php
<?php

class RutaController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Ruta;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Ruta']))
		{
			$model->attributes=$_POST['Ruta'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->idRuta));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Ruta']))
		{
			$model->attributes=$_POST['Ruta'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->idRuta));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Ruta');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Ruta('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Ruta']))
			$model->attributes=$_GET['Ruta'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Ruta::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='ruta-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/ruta/_form.php
<div style="width:100%">
	<div id="mapdiv" style="width:100%; height:600px;">
        
    </div>

	<script type="text/javascript">
	  	var map;
	  	var created = false;
	  	var lastmarker;

	  	function mapa()

	  	{

	    //var opts = {'center': new google.maps.LatLng(26.12295, -80.17122), 'zoom':11, 'mapTypeId': google.maps.MapTypeId.ROADMAP }
	   	var opts = {'center': new google.maps.LatLng(-18.487171, -70.306298), 'zoom':13, 'mapTypeId': google.maps.MapTypeId.ROADMAP }
	   	map = new google.maps.Map(document.getElementById('mapdiv'),opts);
	   	var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';

	   	var camino = new google.maps.MVCArray();
	   	<?php if (!$model->isNewRecord): ?>

	   		var camino = google.maps.geometry.encoding.decodePath("<?php echo $model->textoRuta?>");
	   		var caminoOriginal = camino;

	   	<?php endif;?>



	   	var optpoly = {
	   		path: camino,
	   		strokeColor: "#55acee", strokeWeight: 5
	   	};

	   	var polilinea = new google.maps.Polyline(optpoly);

	   	polilinea.setMap(map);



	    google.maps.event.addListener(map,'click',function(event) {

	    	var camino = polilinea.getPath();
	    	
	    	var lat = event.latLng.lat();
	    	var long = event.latLng.lng();

	    	camino.push ( event.latLng);

	    	//console.log(camino.getArray().toString());


	    	var string = google.maps.geometry.encoding.encodePath(camino).replace(/\\/g,"\\\\");

	    	console.log(string);

	    	document.getElementById('Ruta_textoRuta').value = string; 
	    	//document.getElementById('ZonaSegura_latitudZS').value = str.toString().substring(0, 11);



	   	});

  		$("#delete").click(function(){
    		var run = polilinea.getPath();
    		run.clear();
    		document.getElementById('Ruta_textoRuta').value = "";

		});

  		<?php if (!$model->isNewRecord): ?>

	   		var bounds = new google.maps.LatLngBounds();
    		var points = polilinea.getPath().getArray();
    		for (var n = 0; n < points.length ; n++){
        		bounds.extend(points[n]);
    		}
    		map.fitBounds(bounds);

  			$("#reset").click(function(){
    			var run = polilinea.getPath();
    			run.clear();
    			var optpoly = {
	   				path: camino,
	   				strokeColor: "#55acee", strokeWeight: 5
	   			};
    			polilinea.setOptions(optpoly);
    			var string = google.maps.geometry.encoding.encodePath(camino);
    			document.getElementById('Ruta_textoRuta').value = string;
			});

	   	<?php endif;?>


	  	}


  	</script>
  	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9_FJ8r7K4pNJPfNLOrYsY1sk6fyEdtP0&libraries=geometry&callback=mapa" async defer></script>
</div>
<br/>
<div id="delete">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
    'label'=>'Reiniciar',
    'type'=>'primary', // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
    'size'=>'large', // null, 'large', 'small' or 'mini'
    'htmlOptions'=>array(
    	'style'=>'display:inline-block',
    	'class'=>'botonForm',
    	),
)); ?>
</div>


<?php if (!$model->isNewRecord){
	echo '<div id="reset">';
	$this->widget('bootstrap.widgets.TbButton', array(
    'label'=>'Camino Original',
    'type'=>'primary', // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
    'size'=>'large', // null, 'large', 'small' or 'mini'
    'htmlOptions'=>array(
    	'style'=>'display:inline-block',
    	'class'=>'botonForm',
    	),
)); 
	echo '</div>';
}
?>
<br/>



<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'ruta-form',
	'enableAjaxValidation'=>false,
)); ?>
<br/><br/>
	<p class="help-block">Los campos con <span class="required">*</span> son necesarios.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'nombreRuta',array('class'=>'span5','maxlength'=>45)); ?>

	<?php 
	$hoy = date("Y-m-d"); 
	echo $form->hiddenField($model,'fechaRuta',array('value'=>$hoy)); ?>

	<?php echo $form->hiddenField($model,'textoRuta',array('class'=>'span5','maxlength'=>50000)); ?>

	<?php echo $form->hiddenField($model,'usuario_idUsuario',array('value'=>Yii::app()->user->getId())); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Crear' : 'Guardar',
			'htmlOptions'=>array(
				'class'=>'botonForm',
				),
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/ruta/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'idRuta',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'nombreRuta',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->textFieldRow($model,'fechaRuta',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->textFieldRow($model,'textoRuta',array('class'=>'span5','maxlength'=>45)); ?>

	<?php echo $form->textFieldRow($model,'usuario_idUsuario',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Buscar',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/ruta/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('idRuta')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idRuta),array('view','id'=>$data->idRuta)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nombreRuta')); ?>:</b>
	<?php echo CHtml::encode($data->nombreRuta); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fechaRuta')); ?>:</b>
	<?php echo CHtml::encode($data->fechaRuta); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('textoRuta')); ?>:</b>
	<?php echo CHtml::encode($data->textoRuta); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('usuario_idUsuario')); ?>:</b>
	<?php echo CHtml::encode($data->usuario_idUsuario); ?>
	<br />


</div>

protected/views/ruta/create.php
<?php
$this->breadcrumbs=array(
	'Rutas'=>array('index'),
	'Crear',
);

$this->menu=array(
	array('label'=>'Listar Ruta','url'=>array('index')),
	//array('label'=>'Administrar Ruta','url'=>array('admin')),
);
?>

<h1>Nueva Ruta</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/ruta/index.php
<?php
$this->breadcrumbs=array(
	'Rutas',
);

$this->menu=array(
	array('label'=>'Crear Ruta','url'=>array('create')),
	//array('label'=>'Administrar Ruta','url'=>array('admin')),
);
?>

<h1>Rutas</h1>

<div class="coloradd icon-block">
<a href="<?php echo Yii::app()->createUrl('ruta/create',array());?>">
<img class="mas" src="<?php echo Yii::app()->theme->baseUrl; ?>/img/mas.png">
<span>Nuevo</span>
</a>
</div>
<table class="responstable" style="margin-top: 60px;">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Fecha de Creación</th>
			<th>Acciones</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	$lista = Ruta::model()->findAll();
	if($lista)
	{
		foreach ($lista as $Item) {
			echo '<tr>';
			echo '<td>';
			echo $Item->nombreRuta;
			echo '</td>';
			echo '<td>';
			echo $Item->fechaRuta;
			echo '</td>';

			echo '<td class="opcionestable">';
			echo '<a href="'.Yii::app()->createUrl('ruta/view',array('id'=>$Item->idRuta)).'"><img class="imagenView" src="/onemi-prev/themes/bootstrap/img/ver.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('ruta/update',array('id'=>$Item->idRuta)).'"><img class="imagenView" src="/onemi-prev/themes/bootstrap/img/editar.png"></a>';
			echo '<a href="'.Yii::app()->createUrl('ruta/delete',array('id'=>$Item->idRuta)).'"><img class="imagenView" src="/onemi-prev/themes/bootstrap/img/borrar.png"></a>';
			echo '<i  aria-hidden="true"></i>';
			echo '</td>';
			echo '</tr>';
		}
	}
	?>
	
		
	</tbody>
</table>


<?php 

//$this->widget('bootstrap.widgets.TbListView',array(	'dataProvider'=>$dataProvider,	'itemView'=>'_view',)); 

?>

protected/views/ruta/update.php
<?php
$this->breadcrumbs=array(
	'Rutas'=>array('index'),
	$model->idRuta=>array('view','id'=>$model->idRuta),
	'Update',
);

$this->menu=array(
	array('label'=>'Listar Ruta','url'=>array('index')),
	array('label'=>'Crear Ruta','url'=>array('create')),
	array('label'=>'Ver Ruta','url'=>array('view','id'=>$model->idRuta)),
	//array('label'=>'Administrar Ruta','url'=>array('admin')),
);
?>

<h1>Modificar Ruta <?php echo $model->idRuta; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/ruta/view.php
<?php
$this->breadcrumbs=array(
	'Rutas'=>array('index'),
	$model->idRuta,
);

$this->menu=array(
	array('label'=>'Listar Ruta','url'=>array('index')),
	array('label'=>'Crear Ruta','url'=>array('create')),
	array('label'=>'Modificar Ruta','url'=>array('update','id'=>$model->idRuta)),
	array('label'=>'Eliminar Ruta','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->idRuta),'confirm'=>'Esta seguro de eliminar este item?')),
	//array('label'=>'Administrar Ruta','url'=>array('admin')),
);
?>

<h1><?php echo $model->nombreRuta; ?></h1>


	<div style="width:90%; height:400px; margin: auto;" id="map">

	</div>

<script>
<?php 
echo "
	var map;
	function initMap() {

        var mapDiv = document.getElementById('map');

        //añadir mapa
        var opts = {'center': new google.maps.LatLng(-18.487171, -70.306298), 'zoom':13, 'mapTypeId': google.maps.MapTypeId.ROADMAP }
	   	map = new google.maps.Map(document.getElementById('map'),opts);
	   	
	   	var camino = google.maps.geometry.encoding.decodePath('".$model->textoRuta."');

	   	console.log(camino);
	    var optpoly = {
	    	editable: false,
	    	path: camino,
	   		strokeColor: '#55acee', strokeWeight: 5
	   	};

	   	var polilinea = new google.maps.Polyline(optpoly);

	   	polilinea.setMap(map);

	   	var bounds = new google.maps.LatLngBounds();
    	var points = polilinea.getPath().getArray();
    	for (var n = 0; n < points.length ; n++){
        	bounds.extend(points[n]);
    	}
    	map.fitBounds(bounds);
	    
	    //map.fitBounds(polilinea.getBounds());
}
        
	
       
";
?>
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9_FJ8r7K4pNJPfNLOrYsY1sk6fyEdtP0&libraries=geometry&callback=initMap" async defer></script>